# Generated by Django 3.2.6 on 2022-10-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_tag_vlaue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='vlaue',
            new_name='value',
        ),
    ]
